doctrine_migrations:
  storage:
    table_storage:
      table_name: 'migration_versions'

  migrations_paths:
    'DoctrineMigrations': '%kernel.project_dir%/database/migrations'
  enable_profiler: '%kernel.debug%'
