security:
  enable_authenticator_manager: true
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
  providers:
    db_users:
      entity:
        class: App\Entity\User
        property: username
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: db_users
      form_login:
        login_path: login
        check_path: login
      logout:
        path: /logout
        target: /

  access_control:
   - { path: '^/login', roles: PUBLIC_ACCESS }
   - { path: '^/', roles: ROLE_USER }
