version: "3"

services:
  app-nginx:
    container_name: app-nginx
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    links:
      - app-php
  app-php:
    container_name: app-php
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - 9000
    links:
      - app-mysql
  app-mysql:
    container_name: app-mysql
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    ports:
      - 3306
