version: "3"

services:
  app:
    build:
      context: docker/app
      dockerfile: Dockerfile
    ports:
      - 8000:8080
    volumes:
      - .:/var/www/html
    links:
      - mysql
  mysql:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    ports:
      - "3306"
